import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Footer } from '@/components/molecules/Footer';
import { Providers } from '@/redux/cart/Providers';
import { RouterContextProvider } from '@/contexts/RouterContext';
import { GoogleAnalytics } from '@/components/atoms/GoogleAnalytics';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'UrbanFinds',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleAnalytics />
        <Providers>
          <RouterContextProvider>{children}</RouterContextProvider>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
